### PR TITLE
Temp fix to get .NET 8 into devcontainer

### PR DESCRIPTION
**Pull request by codemillmatt**
@glaucia86 - this is a _hack_ to get .NET 8 going in a devcontainer. It'll work until the universal image is updated to .NET 8. I'm creating the PR in draft mode for now so you can take a look at it.

### CODE REVIEW

**Comment by glaucia86** [comment]
Thanks a lot for your contribution on this, @codemillmatt!

**Comment by glaucia86** [comment]
@codemillmatt hi! I made a test.... rebuilded the `devcontainer.json` as you included here... and again I'm still receiving the same error:

image

**Comment by codemillmatt** [comment]
My bad @glaucia86 - I was messing around some and the devcontainer file was different. The one in the PR now should be better. It's using the base Ubuntu image and installing python & .NET as features.

**Comment by glaucia86** [comment]
> My bad @glaucia86 - I was messing around some and the devcontainer file was different. The one in the PR now should be better. It's using the base Ubuntu image and installing python & .NET as features.

I will test tomorrow. 😊
I will let you know

**Pull request closed without merging**
