### PR TITLE
Correcting Broken Links

### PR DESCRIPTION
**Pull request by shahpreetk**
Correcting broken links that have moved with the new URL

### CODE REVIEW

**Comment by shahpreetk** [comment]
Fixed 22/26 broken URLs. 

Not sure why the last 4 are failing as they seem to be working fine.

**Comment by koreyspace** [comment]
Hi @shahpreetk , thanks for this contribution. Can you explain the move to this url for the Discord - https://dcbadge.limes.pink/api/server/ByRwuEEgH4 ?

**Comment by shahpreetk** [comment]
Hi @koreyspace, 
I changed the older link as it was showing as a broken URL(https://dcbadge.vercel.app/api/server/ByRwuEEgH4) and is redirecting to https://dcbadge.limes.pink/api/server/ByRwuEEgH4

**Comment by IsuminI** [comment]
Hello!
The remaining four URL issues were resolved with the update to the [markdown checker version 0.2.3.](https://github.com/john0isaac/markdown-checker/issues/85)
If you push an empty commit to rerun the GitHub Actions, the problem should be fixed.

Additionally, regarding the PR (#639) we submitted, is it acceptable to run the action using some of the updated URLs from this PR to pass the URL check?

**Review by koreyspace — APPROVED** [review]

**Pull request merged**
