### PR TITLE
Add Spanish (Mexico) es-mx translation

### PR DESCRIPTION
**Pull request by icebeam7**
Along with [Pablo Piovano](https://github.com/ppiova) (@ppiova) we submit a PR that translates the repository to Spanish (Mexico) language. I will update this comment each time a new commit is confirmed in our fork with the modules that have been translated:

* ~~Initial README~~ (not needed anymore)
* ~~Module 0~~ (not needed anymore)
* ~~Module 1~~ (not needed anymore)
* Module 2
* Module 3
* Module 5
* Module 7 (*New* added on Feb 3rd)
* Module 4 (*New* added on Feb 4th)

This PR references #83 and is submitted for your consideration and review. Thank you.

### CODE REVIEW

**Comment by icebeam7** [comment]
> @microsoft-github-policy-service agree

@microsoft-github-policy-service agree

**Comment by icebeam7** [comment]
¡Gracias @abrilurena por tu comentario! Cada semana tratamos de traducir uno o dos módulos, iré actualizando el comentario principal cuando tengamos listos los siguientes (estoy en proceso de terminar el 7). 

Quedamos atentos de cómo quedan las asignaciones para que todos los interesados podamos contribuir en este esfuerzo conjunto :)

**Comment by koreyspace** [comment]
@abrilurena or @icebeam7 can you please look into these conflicts?

**Comment by icebeam7** [comment]
@koreyspace thanks for your comment, the issue has just been resolved. I removed the conflicting files from my local repo and sent a PR here. The files were no longer needed from my side as their corresponding translations were pushed in the main repo a few weeks ago. Thank you!

**Pull request closed without merging**
