### PR TITLE
fix: typos and grammar 00-06

### PR DESCRIPTION
**Pull request by john0isaac**
- Fixed multiple typos, and repetition of words.
- Improved the grammar of the READMEs and notebooks.

### CODE REVIEW

**Review by softchris — APPROVED** [review]

**Review by leestott — APPROVED** [review]
@john0isaac  thanks for the corrections great work from a Gold Student Ambassador @koreyspace

**Comment by softchris** [comment]
huge thank you :) @john0isaac

**Comment by john0isaac** [comment]
@leestott, @softchris 
I was going to fix the readme only but thought I would give it a go and look into all the exercises.
Don't merge give me like 40 mins and it will be ready.

**Comment by john0isaac** [comment]
The exercises got bigger as I progressed.
I will pick it up again tomorrow around the same time.
@leestott, Feel free to merge this pull request as it has lots of improvements.

**Review by leestott — APPROVED** [review]

**Pull request merged**
