### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Whitegabriella789**
Revised the README by editing some grammatical errors and added a key terms section for easier beginner-friendly readability.

### CODE REVIEW

**Comment by Whitegabriella789** [comment]
I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer. I agree to the CLA.

**Review by koreyspace — APPROVED** [review]

**Review by koreyspace — APPROVED** [review]

**Comment by koreyspace** [comment]
@Whitegabriella789 the command is @microsoft-github-policy-service agree if you are not representing a company

**Comment by Whitegabriella789** [comment]
My apologies. I'm still learning GitHub. @microsoft-github-policy-service agree

**Comment by Whitegabriella789** [comment]
@microsoft-github-policy-service agree

**Review by koreyspace — APPROVED** [review]

**Pull request merged**
