### PR TITLE
Fix#544

### PR DESCRIPTION
**Pull request by bmerkle**
This is a fix for bug #544

### CODE REVIEW

**Comment by bmerkle** [comment]
@microsoft-github-policy-service agree [company="SICK-AG"

**Comment by bmerkle** [comment]
@microsoft-github-policy-service agree [company="SICK-AG"]

**Comment by bmerkle** [comment]
@microsoft-github-policy-service agree company="SICK-AG"

**Review by panchamnarng30 — CHANGES_REQUESTED** [review]
write readable code in the

**Review by koreyspace — APPROVED** [review]

**Pull request merged**
